source 'https://rubygems.org'
ruby "2.0.0"
group :development, :test do
  gem 'openstack'
  gem 'nova'
  gem 'net-ssh-simple'
  # gem fog
  # gem 'activesupport', '~>4.0'
  # gem 'librarian-puppet'
  # gem 'rspec_junit_formatter'
end